[package]
name = "dota-localization-changer"
version = "3.0.0"
edition = "2021"

[dependencies]
qmetaobject = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
cstr = "0.2"
valve_pak = "0.1"

[profile.dist]
inherits = "release"
lto = "thin"
codegen-units = 1
strip = true